### ISSUE TITLE
Level Viewer not working at all

### ISSUE THREAD

**Issue by Neeebula** [AdrianoDiDio/Medal-Of-Honor-PSX-File-Viewer#1]
Windows 10 x64, double click/admin rights nothing. Can't get it to boot it up

**Comment by AdrianoDiDio** [comment]
Hi, In order to run It you need to have a copy of Medal Of Honor for PSX extracted on some folder on your pc then you need to open up a cmd prompt and navigate to the folder where MOHLevelViewer.exe is and type:
MOHLevelViewer.exe FullPath MissionNumber LevelNumber
E.G If you have extracted on C:\MOHPSX and you want to see Mission 1 Level 1 then the command is:
MOHLevelViewer.exe C:\MOHPSX 1 1
I've tested it on Windows 7 and It should work...

**Comment by Neeebula** [comment]
It's working fine, thanks for the heads up ! Even though everything works perfectly fine I'm receiving this error: 
![1](https://user-images.githubusercontent.com/75518400/101256196-96e47300-371f-11eb-87ff-c08b5b3a72a8.png)

**Comment by AdrianoDiDio** [comment]
I've updated the binaries for Linux and Windows since a few things changed since last release...
That error is strange because I've tested all the Mission/Level combination on windows and It never showed up..
Can you please tell me what Medal Of Honor version are you using (just need the slus/sles number of the executable) ?

**Comment by Neeebula** [comment]
Medal of Honor version that I'm using is: SLES-02470, according to the CD-ROM tags is MoH PAL-UK

**Comment by AdrianoDiDio** [comment]
I've got a different version so I can't really tell...
Anway since that check was not necessary I've removed it and updated the release page...Let me know if It works now...

**Comment by Neeebula** [comment]
Everything works just fine now, thank you so much for the help and the awesome tool !

**Comment by AdrianoDiDio** [comment]
Thanks!
I'd like to thank you aswell for opening this issue, hopefully now It should work with all the version (NTSC/PAL) that are available...
