### ISSUE TITLE
Im lost

### ISSUE THREAD

**Issue by Vyshtar** [AdrianoDiDio/Medal-Of-Honor-PSX-File-Viewer#10]
Hey hello, i'm trying to use the model viewer to export stuff, but i can't even load the .bin file into the viewer, where do i even start? do i have to decode the .bin file with another program to see the files? how do i do it?

**Comment by AdrianoDiDio** [comment]
Hello, if you are talking about the bin/cue format then yes, you would have to extract it or mount it to a directory in order for these tools to work.
On Linux there is a tool that can either mount it to a folder or convert it to ISO in order to later extract it but, if you are on windows, then you would have to search for a similar tool.
Once extracted you can feed the *.BSD files directly to MOHModelViewer, while MOHLevelViewer will ask for the directory where the DATA folder is.
Let me know if you manage to solve the issue or need any help with the tools.

**Comment by Vyshtar** [comment]
Okay, i use the jpsxdec to decode audio so i can browse everything, how do i decode textures, levels, animations, models and other stuff?

**Comment by AdrianoDiDio** [comment]
Well, if you want to just see/extract models and textures then you could use that tool to extract all the files.
One thing I'm not sure is whether or not that tool can extract all the folders...because while MOHModelViewer/TIMViewer/SoundExplorer works with single files (for example MOHModelViewer expects a BSD file e.g 1_1.BSD and a corresponding 1_10.TAF in the same directory) for it to work, other tools requires the whole folder layout.
This means that you have to either find a way to extract all the folders and files with JPSXDec or use a different tool that let you extract (or mount) the cd image to a specific directory that you can then select in MOHLevelViewer/SSTViewer. 

EDIT
I'm gonna close this issue, if you need any more help feel free to re-open this one or create a new one.
