### ISSUE TITLE
Exporting levels into 3D model?

### ISSUE THREAD

**Issue by vrpixel** [AdrianoDiDio/Medal-Of-Honor-PSX-File-Viewer#2]
I was just searching about MOH PSX extension, and came up upon this project. Awesome. Are there any plans for implementing some 3D format exporter, like OBJ or FBX? Perhaps it's already possible?
Thanks for all your work, the level viewer works well.

**Comment by AdrianoDiDio** [comment]
Thanks, at the moment I have not implemented such a feature but should be easy to do since it's a matter of exporting the data that is already loaded in the MOHLevelViewer program along with the VRAM textures that are generated for each level at runtime.
I may add this feature at a later time, maybe after understanding how 3D models are defined along with their animations.
If you want you can create a pull request to add such a feature to export the level data to another file format.

**Comment by vrpixel** [comment]
Unfortunatetly I can't really code, so I'll have to be patient.

**Comment by AdrianoDiDio** [comment]
Check issue  #3 for updates on the status of this feature.
