### ISSUE TITLE
Misaligned FP weapons

### ISSUE THREAD

**Issue by Nitestokeh** [AdrianoDiDio/Medal-Of-Honor-PSX-File-Viewer#5]
Greetings,
Noticed this with Garand, it's the same for all animations:
![image](https://user-images.githubusercontent.com/11159125/186961302-5bebab2d-17ed-4b9b-b885-fce34bb2bfca.png)
I understand the tools are still being worked on but I thought it would be helpful to report such issue

I would also like to make some suggestions:

- For camera movement, would it be possible to make it move on RMB? Some models are offset and impossible to view properly
- Would it be possible to export character models in T-pose?

**Comment by AdrianoDiDio** [comment]
Thanks for the feedback.

The animation were misaligned due to a missing quaternion in the list that was causing the animation to not be complete (same issue could be seen on the Bazooka,Sniper Rifle and ID papers) and will be fixed in the next release.

> For camera movement, would it be possible to make it move on RMB? Some models are offset and impossible to view properly

I've added the ability to strafe left-right and move vertically up-down...I'll test whether or not it is enough to manually center the model, otherwise I'll implement a free-view camera.

> Would it be possible to export character models in T-pose?

I don't have much experience on how animations works and I'm not sure on how to obtain it (or if it is even possible in this case)...

I'll keep this issue open until the next release, if you have any other feedback feel free to add it here.

**Comment by Nitestokeh** [comment]
For T-poses, you could integrate a format that actually exports bones for models — .fbx or .smd. Having these would be already enough if one wants to change the pose themselves

**Comment by AdrianoDiDio** [comment]
Unfortunately bones are stored in a different way than the usual one and it would require some work to convert it to another format, moreover I'd like not to use an external library just to export it (like fbx) .
I'll check if there are simpler file formats to export animations (like ply for static objects ) that are ASCII based and do not require any third party library.

**Comment by AdrianoDiDio** [comment]
I'm going to close this issue since It should be solved now, if not, feel free to re-open it or open a new one.
Regarding the possibility to export it to a different format:
I've tried to implement an MD5 and IQM exporter but unfortunately, as stated before, due to the way the skeletal hierarchy data is stored, makes thing a lot harder to export it to an open format.
One potential solution could be to write a custom importer plugin to support the format used by Medal Of Honor, but I don't have any idea on how to write one and for which tool it should be written for.
The only way, for now, to export it  is to use the ply format to obtain a static model using the current selected animation.
