### ISSUE TITLE
Medal of Honor: Underground level viewer issue

### ISSUE THREAD

**Issue by cguy98** [AdrianoDiDio/Medal-Of-Honor-PSX-File-Viewer#8]
![image_2024-02-19_043324792](https://github.com/AdrianoDiDio/Medal-Of-Honor-PSX-File-Viewer/assets/160452030/8d2b7640-625b-463b-b5dd-35ea809272c7)
hi there 
I'm getting this issue when I tried to open level viewer for Medal of Honor: Underground
is there anyway to fix this

**Comment by AdrianoDiDio** [comment]
Hello,
the error you see is due to the way the app works.
While the model viewer requires you to open a specific BSD file, the level viewer only requires the root folder (the one with the DATA folder).
Once loaded, you can use the F3 key to bring up the mission list and change the current level.
Let me know if this solves it so that I can close this issue.

**Comment by cguy98** [comment]
Yeah i got it working
